### ISSUE TITLE
Setup CI Builds via GitHub Actions

### ISSUE THREAD

**Issue by Turnerj** [TurnerSoftware/Pingalot#1]

**Comment by DanielSpindler83** [comment]
Super basic CI Build with GitHub Actions:
Filename = ci-build.yml
Repo File path = .github/workflows

```
name: CI-Build

on:
  push:
    branches: 
    - develop
    - master
  pull_request:
    branches:
    - develop
    - master

jobs:
  build:

    runs-on: windows-latest

    steps:
      
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish Release
      run: dotnet publish --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: PingalotArtifact
        path: D:\a\Pingalot\Pingalot\src\Pingalot\bin\Release\net6.0\publish\*
```
